#!/bin/bash
#
# vc-remove <vc-name>
#
# Remove a VC which was created with pragma_boot script
# It should be only run under normal user account
# Although it does permit root to remove any VC
#
# V0 - 2/24/13, Cindy Zheng, zhengc@sdsc.edu
#

scriptdir=/opt/vc-scripts
vcname=$1

if [ $# != 1 ];
then
  echo "Usage: vm-remove <vc-name>";
  exit 1
fi

#
# Is the VC exist
#
/opt/rocks/bin/rocks list cluster $vcname > /tmp/remove-$vcname.txt
if [ ! -s /tmp/remove-$vcname.txt ];
then
  echo "VC $vcname does not exist";
  /bin/rm -f /tmp/remove-$vcname.txt;
  exit 2
fi

#
# If the user own the VC, remove VC and free the resources
#
username=$(whoami)
if [ "$username" != "root" ];
then
  vcuser=${vcname##*-};
  if [ "$vcuser" != "$username" ];
  then
    echo "Permission denied: Only root or user $vcuser can remove $vcname";
    /bin/rm -f /tmp/remove-$vcname.txt;
    exit 3
  fi
fi

#
# allow user to confirm
#
echo "Ready to remove the following VMs:"
/bin/cat /tmp/remove-$vcname.txt
echo "Confirm (y) or Quit (n)?"
read answer
if [ $answer != "y" ];
then
  echo "Terminate per user request - no VM is removed";
  /bin/rm -f /tmp/remove-$vcname.txt;
  exit
fi

#
# Remove VC
#
echo "sudo $scriptdir/vc-free $vcname $scriptdir/AvailableIP"
sudo $scriptdir/vc-free $vcname $scriptdir/AvailableIP
exit $?
