#!/bin/bash
#
# restore a rocks image after virt-v2v has run
#
#     post_fix_driver image_name_path
#


if [ ! -f "$1" ]; then 
    echo "File $1 is not a machine image"
    exit 1
fi

function error(){
    echo Error $1
    exit 1
}


image="$1"
tmp_folder=`mktemp -d`

# postpatch virt-v2v
guestmount -a $image -m /dev/sda1 $tmp_folder || error "unable to mount guest FS"
cp yum.backup $tmp_folder/etc/yum.conf || error "unable to copy yum.conf"
fusermount -u $tmp_folder || error "unable to unmount $tmp_folder"
sleep 3
rmdir $tmp_folder



