#!/bin/bash
#
# Clem
#
# This script is used to fix network configuration of a node before 
# we boot it
# 
# For info see README



if [ "x$#" != "x4" ]; then
    echo "This script should be invoked with 4 arguments"
    exit 1
fi

function error(){
    echo -e "Error $1"
    exit 1
}

# tree required arguments
temp_disk_path=$1
vc_out_filepath=$2
fqdn=$3
ssh_key=$4


# TODO this should be created dinamically
pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null


tmp_folder=`mktemp -d`


gw=`echo "cat /vc/frontend/public/@gw" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
fqdn=`echo "cat /vc/frontend/public/@fqdn" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
ip=`echo "cat /vc/frontend/public/@ip" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
netmask=`echo "cat /vc/frontend/public/@netmask" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
public_mac=`echo "cat /vc/frontend/public/@mac" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
private_mac=`echo "cat /vc/frontend/private/@mac" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`
dns=`echo "cat /vc/network/dns/@ip" | xmllint --shell $vc_out_filepath | grep = | awk -F \" '{print $2}'`


guestmount -a $temp_disk_path -m /dev/sda1 $tmp_folder || error "unable to mount guest FS"

# create the net_conf.conf
cat >> $tmp_folder/root/net_conf.conf << EOF
public_ip="$ip"
netmask="$netmask"
gw="$gw"
dns="$dns"
fqdn="$fqdn"
#use these two entries to specify new mac addresses
private_mac="$private_mac"
public_mac="$public_mac"
EOF

#copy the ssh key
cat $ssh_key >> $tmp_folder/root/.ssh/authorized_keys

# copy the vc-out.xml
cp $vc_out_filepath $tmp_folder/root/

# remove udev old network rules
rm $tmp_folder/etc/udev/rules.d/70-persistent-net.rules
rm $tmp_folder/etc/sysconfig/network-scripts/ifcfg-eth0
rm $tmp_folder/etc/sysconfig/network-scripts/ifcfg-eth1

fusermount -u $tmp_folder || error "unable to unmount $tmp_folder"




